Algoritmo "salarioaumentado"

Var
// Seção de Declarações das variáveis 
   SN,SA,percentagem: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
    escreva("digite o SN:")
    leia(SN)
   escreva("digite o SA:")
    leia(SA)
    escreva("digite a percentagem:")
    leia(percentagem)



    SN <-(SA+SA*percentagem/100)
    
    escreva(SN)

Fimalgoritmo